### ISSUE TITLE
Official Documentation (Tutorial) + Maven central entry as Javalin plugin

### ISSUE THREAD

**Issue by vvcaw** [javalin/javalin-vite#3] opened 2022-07-23 17:46 UTC
Today we tried our plugin with Javalin version 4.6.1 and it still works. Therefore we would like to create some 'official' documentation / tutorial for our plugin. Maybe that's something for the [community tutorials](https://javalin.io/tutorials/) section of the Javalin website? In order to make it easier for people to follow the tutorial, it would be great if our plugin was part of the official Javalin maven repo, so that people don't have to clone and install the repo locally. 

@tipsy, it would be great if you could help us get started with this process by answering the following questions:
1. Which maven package name should we use for the plugin? (currently: "de.elfsoft:javalin-vite")
2. How does the maven release process actually work then? (ie: which buttons do we need to press once we have a release version ready)
3. Is there a private "development" version of the javalin homepage where we can write the documentation or should we just write a Markdown document and copy it over?

**Comment by dzikoysk** [comment] 2022-07-23 20:56
@tipsy is currently taking a break, but here's something I can already say about this:

The new approach to plugin system is a part of Javalin 5.x, so plugins will get dedicated pages probably closer to the date of official release of v5. We had this conversation on Discord and in general it'll be sth like a marketplace with list of available plugins or sth like that :) Docs site will be probably moved to the main `javalin/javalin` repository to simplify workflow. If you'd like to already start making documentation, I think you can either use README or Wiki in this repository.

Speaking of releases, for Javalin 4.x I think you can just keep `de.elfsoft:javalin-vite` for backwards compatibility. For 5.x I think it'd be nice for users if it'd be just `io.javalin:javalin-vite`. That's the approach I took in [new openapi plugin](https://github.com/javalin/javalin-openapi).

Currently, we're only releasing snapshot builds of 5.x (of Javalin & plugins) to https://maven.reposilite.com/#/snapshots/. Some options to distribute your plugin:
1. You can create GitHub Actions workflow to publish new snapshot per commit ([example](https://reposilite.com/guide/github))
2. You can get your own token to deploy given builds manually
3. If you don't want to manage the distribution for now, you can also just use [JitPack](https://jitpack.io/).

For 1 & 2 just let me know, so I can generate a new access token for this repository and DM me on Discord/Twitter/Email so I can send you those credentials.

For stable 5.x every plugin will probably get official credentials to given path in Maven Central and it'll be distributed by GH Actions as well. Current solution is slightly temporary due to a lot of changes in ecosystem.

**Comment by ClemensElflein** [comment] 2022-10-29 23:09
Hi @dzikoysk,
sorry for the late reply, but we've been busy with other stuff in the meantime. Since @vvcaw is currently building yet another project using javalin-vite, he decided to update it to Javalin 5.

The following has happened:
- He changed the code, so that it works with Javalin 5
- We have removed a bug where vite didn't shutdown in some cases and there were some vite servers lingering around in the background even after restarting the app
- We have migrated the de.elfsoft package to io.javalin to be in line with other javalin packages.
- We have removed the console spam from the vite server, so that the app can finally use the console as intended.


Now I'd like to take on the official maven build, so that using Javalin Vite is easier for the "normal" user. @vvcaw will edit the Readme once this is done.

Last time you said that Javalin deployment stuff is still changing a lot; Is that figured out now? How can we push our plugin to Maven Central?

Thank you!

**Comment by tipsy** [comment] 2022-10-29 23:18
> Last time you said that Javalin deployment stuff is still changing a lot; Is that figured out now? How can we push our plugin to Maven Central?

You need to create a user over at the Sonatype Jira (https://issues.sonatype.org/), then I can tell them to give that user access to `io.javalin.community.vite` (or whatever we choose to call this project). You can then publish on Maven Central.

**Comment by ClemensElflein** [comment] 2022-10-29 23:26
Hi @tipsy! Welcome back and thanks for the quick reply!

I've registered an account. Username: clemenselflein.

Currently we're using `io.javalin.javalin-vite` as maven artifact and we're using `io.javalin.vite` as package.

We'll gladly change it to whatever you like

**Comment by tipsy** [comment] 2022-10-30 10:41
> Hi @tipsy! Welcome back and thanks for the quick reply! 

Thank you ☺️ 

> 've registered an account. Username: clemenselflein.

Great, I've asked them to add you to `io.javalin.community.vite`: https://issues.sonatype.org/browse/OSSRH-84953?focusedCommentId=1213426&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1213426

**Comment by tipsy** [comment] 2022-10-31 19:13
@ClemensElflein subgroup should be available to you now!

**Comment by ClemensElflein** [comment] 2022-11-02 13:42
Hi @tipsy,
thank you! I'll need some help with this.

I have looked into deployment and there is lots of documentation about this. I have also looked at the main javalin repo, but it seems that deployment there uses a legacy config.

I have now added the github workflow and edited the pom.xml to my understanding (see https://github.com/javalin/javalin-vite/tree/chore/deployment), but now I need to add the username and password for deployment as a secret and have the following issues: 

- I'm not sure if that's the same as my sonatype account?
- I can't access the "secrets" settings for the javalin-vite repository. Can you give me access to that?

If you like, you can have a look at my changes and maybe see if I'm missing anything, since it seems too easy. As I understand it, "mvn deploy" will deploy the package and versions with "-SNAPSHOT" will be published to the internal snapshot repo, whereas versions without "-SNAPSHOT" will be made public on maven central automatically.

**Comment by tipsy** [comment] 2022-11-06 10:49
> I'm not sure if that's the same as my sonatype account?

It is.

> I can't access the "secrets" settings for the javalin-vite repository. Can you give me access to that?

Done!

> If you like, you can have a look at my changes and maybe see if I'm missing anything, since it seems too easy. As I understand it, "mvn deploy" will deploy the package and versions with "-SNAPSHOT" will be published to the internal snapshot repo, whereas versions without "-SNAPSHOT" will be made public on maven central automatically.

I've never set this up, I like my legacy solution. Maybe you could have a look @zugazagoitia ?

**Comment by zugazagoitia** [comment] 2022-11-06 11:03
> > I'm not sure if that's the same as my sonatype account?
> 
> It is.
> 

You can also create a dedicated key for deploying on Sonatype iirc. 


> > If you like, you can have a look at my changes and maybe see if I'm missing anything, since it seems too easy. As I understand it, "mvn deploy" will deploy the package and versions with "-SNAPSHOT" will be published to the internal snapshot repo, whereas versions without "-SNAPSHOT" will be made public on maven central automatically.
> 
> I've never set this up, I like my legacy solution. Maybe you could have a look @zugazagoitia ? 

I don't think this happens automatically, it might be mentioned in the Maven central documentation. In my case I have declared separate repositories for versions containing `-SNAPSHOT`, and I'm using the sonatype plugin to release to maven central. It's not a maven config, but a Gradle one, you can check it out on my repo (javalin/javalin-ssl) and maybe @dzikoysk has something similar on his openapi plugin. If you need more help we can talk over a discord thread and I'll help you with what I can.

**Comment by ClemensElflein** [comment] 2022-11-17 10:26
Thank you for the info! I was finally able to successfully publish to maven central! 🎉 

So satisfying to just open the example project in Intellij, press play and get a Javalin Vue (or Svelte) instance with hot reloading. Maybe some people start using it as well.

@tipsy there's a feature called "template repositories" where you can put a project (like our example folders here) and people can just derive their own repo with one button click. Do you think we could / should do this?

Docs here if you don't know:
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

I'll close this one, since it's done.

**Closed as completed by ClemensElflein** 2022-11-17 10:26 UTC
Labels: documentation, help wanted

**Comment by tipsy** [comment] 2022-11-17 10:53
> So satisfying to just open the example project in Intellij, press play and get a Javalin Vue (or Svelte) instance with hot reloading. Maybe some people start using it as well.

Tutorial? 😁 

> @tipsy there's a feature called "template repositories" where you can put a project (like our example folders here) and people can just derive their own repo with one button click. Do you think we could / should do this?

We actually have one, it's used for a couple of our repos: https://github.com/javalin/javalin-repo-template

Were you thinking for Javalin internal stuff, or for example a JavalinVite starter project?

**Comment by ClemensElflein** [comment] 2022-11-17 13:17
> Tutorial? 😁
Hopefully soon @vvcaw  ;-)

> Were you thinking for Javalin internal stuff, or for example a JavalinVite starter project?
I was thinking for javalin-vite starter projects. I.e. click the use-template button, clone and play.

**Comment by tipsy** [comment] 2022-11-17 13:31
> I was thinking for javalin-vite starter projects. I.e. click the use-template button, clone and play.

Sure, let's set it up as part of the tutorial.
